#pragma once

#include "core_controller.h"
#include "crash_log.h"
#include "catalog_feed_loader.h"
#include "catalog_controller.h"
#include "catalog_cover_coordinator.h"
#include "catalog_filter_service.h"
#include "catalog_discovery_service.h"
#include "catalog_parser.h"
#include "cover_image_cache.h"
#include "file_utils.h"
#include "i18n.h"
#include "install_analyzer.h"
#include "install_heuristics.h"
#include "install_kind_probe_service.h"
#include "install_session_service.h"
#include "game_metadata_service.h"
#include "http_download_session.h"
#include "job_orchestrator.h"
#include "job_status.h"
#include "launch_resolver.h"
#include "library_controller.h"
#include "library_maintenance_service.h"
#include "game_update_service.h"
#include "launch_controller.h"
#include "plugin_host.h"
#include "plugin_catalog_service.h"
#include "plugin_interface.h"
#include "steam_source_plugin.h"
#include "process_launcher.h"
#include "process_tracker.h"
#include "runtime_dependency_service.h"
#include "proton_manager.h"
#include "windows_runner.h"
#include "storage_library_model.h"
#include <QCoreApplication>
#include <QDateTime>
#include <QDesktopServices>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QGuiApplication>
#include <QClipboard>
#include <QJsonDocument>
#include <QJsonObject>
#include <QSettings>
#include <QStandardPaths>
#include <QTimer>
#include <QUrl>
#include <QJSEngine>
#include <QQmlEngine>
#include <QtQml/qqml.h>
#if defined(Q_OS_WIN)
#include <objbase.h>
#include <shobjidl.h>
#else
#include <QFileDialog>
#endif
